const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
$('#year').textContent=new Date().getFullYear();
const nav=$('#navlinks'); $('#menu').addEventListener('click',()=>nav.classList.toggle('open')); $$('#navlinks a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const progress=$('#progress'); window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(scrollY/Math.max(h,1)*100)+'%';},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12}); $$('.reveal').forEach(e=>io.observe(e));
// Offer carousel: desktop shows 3, tablet 2, mobile 1.
const track=$('#offerTrack'), cards=$$('.offer'), dots=$('#offerDots'); let offerIndex=0; const getVisible=()=>innerWidth<=720?1:innerWidth<=1050?2:3; function renderOfferDots(){dots.innerHTML=''; const pages=Math.max(1,cards.length-getVisible()+1);for(let i=0;i<pages;i++){const b=document.createElement('button');b.className=i===offerIndex?'active':'';b.onclick=()=>goOffer(i);dots.appendChild(b)}} function goOffer(i){const max=Math.max(0,cards.length-getVisible());offerIndex=Math.min(Math.max(i,0),max);const w=cards[0].getBoundingClientRect().width+18;track.scrollTo({left:offerIndex*w,behavior:'smooth'});renderOfferDots()} $('#offerSlider .prev').onclick=()=>goOffer(offerIndex-1);$('#offerSlider .next').onclick=()=>goOffer(offerIndex+1);addEventListener('resize',()=>{offerIndex=Math.min(offerIndex,Math.max(0,cards.length-getVisible()));renderOfferDots()});renderOfferDots(); let offerTimer=setInterval(()=>goOffer(offerIndex>=cards.length-getVisible()?0:offerIndex+1),6000); $('#offerSlider').addEventListener('mouseenter',()=>clearInterval(offerTimer));
// Product carousel
const slides=$$('.slide'), pdots=$('#productDots'), captions=['Vista producto · Escritorio + móvil','Dashboard · Control y visualización','Análisis · Ingresos, gastos y tendencias'];let pi=0;slides.forEach((_,i)=>{const b=document.createElement('button');b.className=i===0?'active':'';b.onclick=()=>goProduct(i);pdots.appendChild(b)});function goProduct(i){pi=(i+slides.length)%slides.length;slides.forEach((s,j)=>s.classList.toggle('active',j===pi));$$('#productDots button').forEach((b,j)=>b.classList.toggle('active',j===pi));$('#productCaption').textContent=captions[pi]}$('#pPrev').onclick=()=>goProduct(pi-1);$('#pNext').onclick=()=>goProduct(pi+1);let productTimer=setInterval(()=>goProduct(pi+1),5500);$('#productStage').addEventListener('mouseenter',()=>clearInterval(productTimer));
// WhatsApp: insert the future WOM number here, country code included, e.g. 569XXXXXXXX.
const WHATSAPP_NUMBER=''; const defaultMsg='Hola, Somos Software. Me interesa conocer sus soluciones digitales.'; const wa=$('#waButton'); function setWA(){wa.href=WHATSAPP_NUMBER?'https://wa.me/'+WHATSAPP_NUMBER+'?text='+encodeURIComponent(defaultMsg):'#contacto'} setWA(); $$('.offer [data-offer]').forEach(a=>a.addEventListener('click',e=>{if(!WHATSAPP_NUMBER){e.preventDefault();alert('El número WhatsApp comercial aún no está configurado.');return}wa.href='https://wa.me/'+WHATSAPP_NUMBER+'?text='+encodeURIComponent('Hola, Somos Software. Me interesa la oferta: '+a.dataset.offer+'.');}));
